services:
  - type: web
    name: blokus-bomberman
    runtime: docker
    plan: free
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
        sync: false
      - key: PHX_HOST
        sync: false
      - key: PHX_SERVER
        value: "true"
      - key: PORT
        value: "4000"
    dockerfilePath: ./Dockerfile
    dockerContext: .
